from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

contenedores = [
    {
        'status':    'EN DESCARGA',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN DESCARGA',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN DESCARGA',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN DESPACHO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN DESPACHO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN PUERTO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN PUERTO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN PUERTO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN PUERTO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN PUERTO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN PUERTO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGELADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
    {
        'status':    'EN TRANSITO',
        'proveedor': 'CONGEASASLADOS DE NAVARRA',
        'ctr':       '249',
        'producto':  'BROCOLI CONGELADO 500 GRS DP',
        'cantidad':  '14.700',
        'um':        'KILOS',
        'categoria': 'B',
        'carga':     'PALETIZADA',
        'tipo':      'REEFER',
        'eta':       '25-05-2021',
        'retiro':    '27-05-2021',
        'hora':      '15:37',
        'siglactr':  'CXRU1617327'
    },
]


def home(request):

    context = {
        'contenedores': contenedores
    }
    return render(request, 'embarques/home.html', context)


def about(request):
    return render(request, 'embarques/about.html', {'title': 'About'})